============================= test session starts ==============================
platform darwin -- Python 3.12.7, pytest-8.4.1, pluggy-1.6.0
rootdir: /Users/johany/Documents/projects/python/fastapi/tt_cyclopedia_back
configfile: pytest.ini
plugins: xdist-3.7.0, anyio-4.9.0, html-4.1.1, Faker-37.4.0, metadata-3.1.1, cov-6.2.1, mock-3.14.1, asyncio-1.0.0
asyncio: mode=Mode.STRICT, asyncio_default_fixture_loop_scope=None, asyncio_default_test_loop_scope=function
collected 0 items / 2 errors

==================================== ERRORS ====================================
______________________ ERROR collecting app/test_main.py _______________________
ImportError while importing test module '/Users/johany/Documents/projects/python/fastapi/tt_cyclopedia_back/app/test_main.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/importlib/__init__.py:90: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
app/test_main.py:3: in <module>
    from app.main import app
app/main.py:10: in <module>
    from app.middleware.log_to_mongo import MongoLoggingMiddleware
app/middleware/log_to_mongo.py:3: in <module>
    from app.config.mongo_config import db
app/config/mongo_config.py:1: in <module>
    from pymongo import MongoClient
E   ModuleNotFoundError: No module named 'pymongo'
__________________________ ERROR collecting app/tests __________________________
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/importlib/__init__.py:90: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
<frozen importlib._bootstrap>:1387: in _gcd_import
    ???
<frozen importlib._bootstrap>:1360: in _find_and_load
    ???
<frozen importlib._bootstrap>:1331: in _find_and_load_unlocked
    ???
<frozen importlib._bootstrap>:935: in _load_unlocked
    ???
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/_pytest/assertion/rewrite.py:186: in exec_module
    exec(co, module.__dict__)
app/tests/conftest.py:6: in <module>
    from app.main import app
app/main.py:10: in <module>
    from app.middleware.log_to_mongo import MongoLoggingMiddleware
app/middleware/log_to_mongo.py:3: in <module>
    from app.config.mongo_config import db
app/config/mongo_config.py:1: in <module>
    from pymongo import MongoClient
E   ModuleNotFoundError: No module named 'pymongo'
=========================== short test summary info ============================
ERROR app/test_main.py
ERROR app/tests - ModuleNotFoundError: No module named 'pymongo'
!!!!!!!!!!!!!!!!!!! Interrupted: 2 errors during collection !!!!!!!!!!!!!!!!!!!!
======================== 6 warnings, 2 errors in 0.75s =========================
